### ISSUE TITLE
Error running as post-build event in Visual Studio 2013

### ISSUE THREAD

**Issue by ThomasBarnekow** [hartez/Acknowledgements#2]
Hi,

I'm trying to run acknowledgements.ps1 after building, using your exact example statement. However, that fails with the following message:

```
The command "if Release == Release powershell -NoProfile -file C:\Visual Studio 2010\Projects\GitHub\ContractArchitect\packages\Acknowledgements.1.0.2\tools\acknowledgements.ps1 C:\Visual Studio 2010\Projects\GitHub\ContractArchitect\ContractArchitect.WebApi\packages.config C:\Visual Studio 2010\Projects\GitHub\ContractArchitect\packages\Acknowledgements.1.0.2\tools\default.cshtml C:\Visual Studio 2010\Projects\GitHub\ContractArchitect\ContractArchitect.WebApi\acknowledgements.html C:\Visual Studio 2010\Projects\GitHub\ContractArchitect\.nuget\NuGet.exe" exited with code -196608.
```

Running from the command line (without the variables, though) works to the point where it doesn't find the Razor library although it is installed. Not sure whether that's even supposed to work.

Anything I can do to make it work?

Thanks, Thomas

**Comment by ThomasBarnekow** [comment]
Having looked at that error message, I enclosed the parameters in double quotes. Therefore,
```
if $(ConfigurationName) == Release powershell -NoProfile -file $(SolutionDir)packages\Acknowledgements.1.0.2\tools\acknowledgements.ps1 $(ProjectDir)packages.config $(SolutionDir)packages\Acknowledgements.1.0.2\tools\default.cshtml $(ProjectDir)acknowledgements.html $(SolutionDir).nuget\NuGet.exe
```
becomes
```
if $(ConfigurationName) == Release powershell -NoProfile -file "$(SolutionDir)packages\Acknowledgements.1.0.2\tools\acknowledgements.ps1" "$(ProjectDir)packages.config" "$(SolutionDir)packages\Acknowledgements.1.0.2\tools\default.cshtml" "$(ProjectDir)acknowledgements.html" "$(SolutionDir).nuget\NuGet.exe"
```
While it now starts to retrieve package information, this leads to the same issue that I ran into when executing the script from the command line:
```
1>  Retrieving package data for acknowledgements
1>  Retrieving data for package 'Antlr'
[further packages omitted]
1>  Retrieving data for package 'WebGrease'
1>  Razor assembly not found; retrieving it from NuGet
1>  'Microsoft.AspNet.Razor 3.2.3' already installed.
1>  [path omitted]\packages\Acknowledgements.1.0.2\tools\acknowledgements.ps1 : The System.Web.Razor assembly must be loaded.
1>      + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
1>      + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,acknowledgements.ps1
```
It does not find  the Razor assembly and then says that Razor is already installed.

What can be done about that?

**Comment by hartez** [comment]
@ThomasBarnekow - I finally had some time to look into this. It's a framework version issue. The script is hard-coded to look for the installed Razor package in a folder path that looks like

`packages\Microsoft.AspNet.Razor.*\lib\net40\System.Web.Razor.dll`

The `net40` part is the problem. If your project is using another framework version (probably 4.5 in your case), the path changes. 

I'm working on fixing this now.

**Comment by ThomasBarnekow** [comment]
@hartez Thank you. Much appreciated.

**Comment by hartez** [comment]
This should be fixed now.

**Comment by ThomasBarnekow** [comment]
Thanks. I'll try it out.
